export const ALL_COUNTRIES = [
  { code: "WORLDWIDE", name: "Worldwide",               flag: "🌍" },
  // Asia
  { code: "AF", name: "Afghanistan",                    flag: "🇦🇫" },
  { code: "AM", name: "Armenia",                        flag: "🇦🇲" },
  { code: "AZ", name: "Azerbaijan",                     flag: "🇦🇿" },
  { code: "BD", name: "Bangladesh",                     flag: "🇧🇩" },
  { code: "BH", name: "Bahrain",                        flag: "🇧🇭" },
  { code: "BN", name: "Brunei",                         flag: "🇧🇳" },
  { code: "BT", name: "Bhutan",                         flag: "🇧🇹" },
  { code: "CN", name: "China",                          flag: "🇨🇳" },
  { code: "GE", name: "Georgia",                        flag: "🇬🇪" },
  { code: "ID", name: "Indonesia",                      flag: "🇮🇩" },
  { code: "IN", name: "India",                          flag: "🇮🇳" },
  { code: "IQ", name: "Iraq",                           flag: "🇮🇶" },
  { code: "IR", name: "Iran",                           flag: "🇮🇷" },
  { code: "IL", name: "Israel",                         flag: "🇮🇱" },
  { code: "JO", name: "Jordan",                         flag: "🇯🇴" },
  { code: "JP", name: "Japan",                          flag: "🇯🇵" },
  { code: "KG", name: "Kyrgyzstan",                     flag: "🇰🇬" },
  { code: "KH", name: "Cambodia",                       flag: "🇰🇭" },
  { code: "KP", name: "North Korea",                    flag: "🇰🇵" },
  { code: "KR", name: "South Korea",                    flag: "🇰🇷" },
  { code: "KW", name: "Kuwait",                         flag: "🇰🇼" },
  { code: "KZ", name: "Kazakhstan",                     flag: "🇰🇿" },
  { code: "LA", name: "Laos",                           flag: "🇱🇦" },
  { code: "LB", name: "Lebanon",                        flag: "🇱🇧" },
  { code: "LK", name: "Sri Lanka",                      flag: "🇱🇰" },
  { code: "MM", name: "Myanmar",                        flag: "🇲🇲" },
  { code: "MN", name: "Mongolia",                       flag: "🇲🇳" },
  { code: "MV", name: "Maldives",                       flag: "🇲🇻" },
  { code: "MY", name: "Malaysia",                       flag: "🇲🇾" },
  { code: "NP", name: "Nepal",                          flag: "🇳🇵" },
  { code: "OM", name: "Oman",                           flag: "🇴🇲" },
  { code: "PH", name: "Philippines",                    flag: "🇵🇭" },
  { code: "PK", name: "Pakistan",                       flag: "🇵🇰" },
  { code: "PS", name: "Palestine",                      flag: "🇵🇸" },
  { code: "QA", name: "Qatar",                          flag: "🇶🇦" },
  { code: "SA", name: "Saudi Arabia",                   flag: "🇸🇦" },
  { code: "SG", name: "Singapore",                      flag: "🇸🇬" },
  { code: "SY", name: "Syria",                          flag: "🇸🇾" },
  { code: "TH", name: "Thailand",                       flag: "🇹🇭" },
  { code: "TJ", name: "Tajikistan",                     flag: "🇹🇯" },
  { code: "TM", name: "Turkmenistan",                   flag: "🇹🇲" },
  { code: "TR", name: "Turkey",                         flag: "🇹🇷" },
  { code: "TW", name: "Taiwan",                         flag: "🇹🇼" },
  { code: "UZ", name: "Uzbekistan",                     flag: "🇺🇿" },
  { code: "VN", name: "Vietnam",                        flag: "🇻🇳" },
  { code: "YE", name: "Yemen",                          flag: "🇾🇪" },
  // Europe
  { code: "AD", name: "Andorra",                        flag: "🇦🇩" },
  { code: "AL", name: "Albania",                        flag: "🇦🇱" },
  { code: "AT", name: "Austria",                        flag: "🇦🇹" },
  { code: "BA", name: "Bosnia and Herzegovina",         flag: "🇧🇦" },
  { code: "BE", name: "Belgium",                        flag: "🇧🇪" },
  { code: "BG", name: "Bulgaria",                       flag: "🇧🇬" },
  { code: "BY", name: "Belarus",                        flag: "🇧🇾" },
  { code: "CH", name: "Switzerland",                    flag: "🇨🇭" },
  { code: "CY", name: "Cyprus",                         flag: "🇨🇾" },
  { code: "CZ", name: "Czech Republic",                 flag: "🇨🇿" },
  { code: "DE", name: "Germany",                        flag: "🇩🇪" },
  { code: "DK", name: "Denmark",                        flag: "🇩🇰" },
  { code: "EE", name: "Estonia",                        flag: "🇪🇪" },
  { code: "ES", name: "Spain",                          flag: "🇪🇸" },
  { code: "FI", name: "Finland",                        flag: "🇫🇮" },
  { code: "FR", name: "France",                         flag: "🇫🇷" },
  { code: "GB", name: "United Kingdom",                 flag: "🇬🇧" },
  { code: "GR", name: "Greece",                         flag: "🇬🇷" },
  { code: "HR", name: "Croatia",                        flag: "🇭🇷" },
  { code: "HU", name: "Hungary",                        flag: "🇭🇺" },
  { code: "IE", name: "Ireland",                        flag: "🇮🇪" },
  { code: "IS", name: "Iceland",                        flag: "🇮🇸" },
  { code: "IT", name: "Italy",                          flag: "🇮🇹" },
  { code: "LI", name: "Liechtenstein",                  flag: "🇱🇮" },
  { code: "LT", name: "Lithuania",                      flag: "🇱🇹" },
  { code: "LU", name: "Luxembourg",                     flag: "🇱🇺" },
  { code: "LV", name: "Latvia",                         flag: "🇱🇻" },
  { code: "MC", name: "Monaco",                         flag: "🇲🇨" },
  { code: "MD", name: "Moldova",                        flag: "🇲🇩" },
  { code: "ME", name: "Montenegro",                     flag: "🇲🇪" },
  { code: "MK", name: "North Macedonia",                flag: "🇲🇰" },
  { code: "MT", name: "Malta",                          flag: "🇲🇹" },
  { code: "NL", name: "Netherlands",                    flag: "🇳🇱" },
  { code: "NO", name: "Norway",                         flag: "🇳🇴" },
  { code: "PL", name: "Poland",                         flag: "🇵🇱" },
  { code: "PT", name: "Portugal",                       flag: "🇵🇹" },
  { code: "RO", name: "Romania",                        flag: "🇷🇴" },
  { code: "RS", name: "Serbia",                         flag: "🇷🇸" },
  { code: "RU", name: "Russia",                         flag: "🇷🇺" },
  { code: "SE", name: "Sweden",                         flag: "🇸🇪" },
  { code: "SI", name: "Slovenia",                       flag: "🇸🇮" },
  { code: "SK", name: "Slovakia",                       flag: "🇸🇰" },
  { code: "UA", name: "Ukraine",                        flag: "🇺🇦" },
  { code: "VA", name: "Vatican City",                   flag: "🇻🇦" },
  // America
  { code: "AR", name: "Argentina",                      flag: "🇦🇷" },
  { code: "BB", name: "Barbados",                       flag: "🇧🇧" },
  { code: "BO", name: "Bolivia",                        flag: "🇧🇴" },
  { code: "BR", name: "Brazil",                         flag: "🇧🇷" },
  { code: "BS", name: "Bahamas",                        flag: "🇧🇸" },
  { code: "BZ", name: "Belize",                         flag: "🇧🇿" },
  { code: "CA", name: "Canada",                         flag: "🇨🇦" },
  { code: "CL", name: "Chile",                          flag: "🇨🇱" },
  { code: "CO", name: "Colombia",                       flag: "🇨🇴" },
  { code: "CR", name: "Costa Rica",                     flag: "🇨🇷" },
  { code: "CU", name: "Cuba",                           flag: "🇨🇺" },
  { code: "DM", name: "Dominica",                       flag: "🇩🇲" },
  { code: "DO", name: "Dominican Republic",             flag: "🇩🇴" },
  { code: "EC", name: "Ecuador",                        flag: "🇪🇨" },
  { code: "GD", name: "Grenada",                        flag: "🇬🇩" },
  { code: "GT", name: "Guatemala",                      flag: "🇬🇹" },
  { code: "GY", name: "Guyana",                         flag: "🇬🇾" },
  { code: "HN", name: "Honduras",                       flag: "🇭🇳" },
  { code: "HT", name: "Haiti",                          flag: "🇭🇹" },
  { code: "JM", name: "Jamaica",                        flag: "🇯🇲" },
  { code: "MX", name: "Mexico",                         flag: "🇲🇽" },
  { code: "NI", name: "Nicaragua",                      flag: "🇳🇮" },
  { code: "PA", name: "Panama",                         flag: "🇵🇦" },
  { code: "PE", name: "Peru",                           flag: "🇵🇪" },
  { code: "PY", name: "Paraguay",                       flag: "🇵🇾" },
  { code: "SR", name: "Suriname",                       flag: "🇸🇷" },
  { code: "SV", name: "El Salvador",                    flag: "🇸🇻" },
  { code: "TT", name: "Trinidad and Tobago",            flag: "🇹🇹" },
  { code: "US", name: "United States",                  flag: "🇺🇸" },
  { code: "UY", name: "Uruguay",                        flag: "🇺🇾" },
  { code: "VE", name: "Venezuela",                      flag: "🇻🇪" },
  // Africa
  { code: "AO", name: "Angola",                         flag: "🇦🇴" },
  { code: "BF", name: "Burkina Faso",                   flag: "🇧🇫" },
  { code: "BI", name: "Burundi",                        flag: "🇧🇮" },
  { code: "BJ", name: "Benin",                          flag: "🇧🇯" },
  { code: "BW", name: "Botswana",                       flag: "🇧🇼" },
  { code: "CD", name: "DR Congo",                       flag: "🇨🇩" },
  { code: "CF", name: "Central African Republic",       flag: "🇨🇫" },
  { code: "CG", name: "Congo",                          flag: "🇨🇬" },
  { code: "CI", name: "Ivory Coast",                    flag: "🇨🇮" },
  { code: "CM", name: "Cameroon",                       flag: "🇨🇲" },
  { code: "CV", name: "Cape Verde",                     flag: "🇨🇻" },
  { code: "DJ", name: "Djibouti",                       flag: "🇩🇯" },
  { code: "DZ", name: "Algeria",                        flag: "🇩🇿" },
  { code: "EG", name: "Egypt",                          flag: "🇪🇬" },
  { code: "ER", name: "Eritrea",                        flag: "🇪🇷" },
  { code: "ET", name: "Ethiopia",                       flag: "🇪🇹" },
  { code: "GA", name: "Gabon",                          flag: "🇬🇦" },
  { code: "GH", name: "Ghana",                          flag: "🇬🇭" },
  { code: "GM", name: "Gambia",                         flag: "🇬🇲" },
  { code: "GN", name: "Guinea",                         flag: "🇬🇳" },
  { code: "GQ", name: "Equatorial Guinea",              flag: "🇬🇶" },
  { code: "GW", name: "Guinea-Bissau",                  flag: "🇬🇼" },
  { code: "KE", name: "Kenya",                          flag: "🇰🇪" },
  { code: "KM", name: "Comoros",                        flag: "🇰🇲" },
  { code: "LR", name: "Liberia",                        flag: "🇱🇷" },
  { code: "LS", name: "Lesotho",                        flag: "🇱🇸" },
  { code: "LY", name: "Libya",                          flag: "🇱🇾" },
  { code: "MA", name: "Morocco",                        flag: "🇲🇦" },
  { code: "MG", name: "Madagascar",                     flag: "🇲🇬" },
  { code: "ML", name: "Mali",                           flag: "🇲🇱" },
  { code: "MR", name: "Mauritania",                     flag: "🇲🇷" },
  { code: "MU", name: "Mauritius",                      flag: "🇲🇺" },
  { code: "MW", name: "Malawi",                         flag: "🇲🇼" },
  { code: "MZ", name: "Mozambique",                     flag: "🇲🇿" },
  { code: "NA", name: "Namibia",                        flag: "🇳🇦" },
  { code: "NE", name: "Niger",                          flag: "🇳🇪" },
  { code: "NG", name: "Nigeria",                        flag: "🇳🇬" },
  { code: "RW", name: "Rwanda",                         flag: "🇷🇼" },
  { code: "SC", name: "Seychelles",                     flag: "🇸🇨" },
  { code: "SD", name: "Sudan",                          flag: "🇸🇩" },
  { code: "SL", name: "Sierra Leone",                   flag: "🇸🇱" },
  { code: "SN", name: "Senegal",                        flag: "🇸🇳" },
  { code: "SO", name: "Somalia",                        flag: "🇸🇴" },
  { code: "SS", name: "South Sudan",                    flag: "🇸🇸" },
  { code: "ST", name: "Sao Tome and Principe",          flag: "🇸🇹" },
  { code: "SZ", name: "Eswatini",                       flag: "🇸🇿" },
  { code: "TD", name: "Chad",                           flag: "🇹🇩" },
  { code: "TG", name: "Togo",                           flag: "🇹🇬" },
  { code: "TN", name: "Tunisia",                        flag: "🇹🇳" },
  { code: "TZ", name: "Tanzania",                       flag: "🇹🇿" },
  { code: "UG", name: "Uganda",                         flag: "🇺🇬" },
  { code: "ZA", name: "South Africa",                   flag: "🇿🇦" },
  { code: "ZM", name: "Zambia",                         flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe",                       flag: "🇿🇼" },
  // Oceania
  { code: "AU", name: "Australia",                      flag: "🇦🇺" },
  { code: "FJ", name: "Fiji",                           flag: "🇫🇯" },
  { code: "FM", name: "Micronesia",                     flag: "🇫🇲" },
  { code: "KI", name: "Kiribati",                       flag: "🇰🇮" },
  { code: "MH", name: "Marshall Islands",               flag: "🇲🇭" },
  { code: "NR", name: "Nauru",                          flag: "🇳🇷" },
  { code: "NZ", name: "New Zealand",                    flag: "🇳🇿" },
  { code: "PG", name: "Papua New Guinea",               flag: "🇵🇬" },
  { code: "PW", name: "Palau",                          flag: "🇵🇼" },
  { code: "SB", name: "Solomon Islands",                flag: "🇸🇧" },
  { code: "TO", name: "Tonga",                          flag: "🇹🇴" },
  { code: "TV", name: "Tuvalu",                         flag: "🇹🇻" },
  { code: "VU", name: "Vanuatu",                        flag: "🇻🇺" },
  { code: "WS", name: "Samoa",                          flag: "🇼🇸" },
];

export type Country = typeof ALL_COUNTRIES[number];

export function getCountry(code: string): Country {
  return ALL_COUNTRIES.find(c => c.code === code) ?? { code, name: code, flag: "🏳️" };
}