import { NextRequest, NextResponse } from "next/server";

export const COUNTRIES: Record<string, { name: string; flag: string }> = {
  // Asia
  AF: { name: "Afghanistan",    flag: "🇦🇫" },
  AM: { name: "Armenia",        flag: "🇦🇲" },
  AZ: { name: "Azerbaijan",     flag: "🇦🇿" },
  BD: { name: "Bangladesh",     flag: "🇧🇩" },
  BH: { name: "Bahrain",        flag: "🇧🇭" },
  BN: { name: "Brunei",         flag: "🇧🇳" },
  BT: { name: "Bhutan",         flag: "🇧🇹" },
  CN: { name: "China",          flag: "🇨🇳" },
  GE: { name: "Georgia",        flag: "🇬🇪" },
  ID: { name: "Indonesia",      flag: "🇮🇩" },
  IN: { name: "India",          flag: "🇮🇳" },
  IQ: { name: "Iraq",           flag: "🇮🇶" },
  IR: { name: "Iran",           flag: "🇮🇷" },
  IL: { name: "Israel",         flag: "🇮🇱" },
  JO: { name: "Jordan",         flag: "🇯🇴" },
  JP: { name: "Japan",          flag: "🇯🇵" },
  KG: { name: "Kyrgyzstan",     flag: "🇰🇬" },
  KH: { name: "Cambodia",       flag: "🇰🇭" },
  KP: { name: "North Korea",    flag: "🇰🇵" },
  KR: { name: "South Korea",    flag: "🇰🇷" },
  KW: { name: "Kuwait",         flag: "🇰🇼" },
  KZ: { name: "Kazakhstan",     flag: "🇰🇿" },
  LA: { name: "Laos",           flag: "🇱🇦" },
  LB: { name: "Lebanon",        flag: "🇱🇧" },
  LK: { name: "Sri Lanka",      flag: "🇱🇰" },
  MM: { name: "Myanmar",        flag: "🇲🇲" },
  MN: { name: "Mongolia",       flag: "🇲🇳" },
  MV: { name: "Maldives",       flag: "🇲🇻" },
  MY: { name: "Malaysia",       flag: "🇲🇾" },
  NP: { name: "Nepal",          flag: "🇳🇵" },
  OM: { name: "Oman",           flag: "🇴🇲" },
  PK: { name: "Pakistan",       flag: "🇵🇰" },
  PH: { name: "Philippines",    flag: "🇵🇭" },
  PS: { name: "Palestine",      flag: "🇵🇸" },
  QA: { name: "Qatar",          flag: "🇶🇦" },
  SA: { name: "Saudi Arabia",   flag: "🇸🇦" },
  SG: { name: "Singapore",      flag: "🇸🇬" },
  SY: { name: "Syria",          flag: "🇸🇾" },
  TH: { name: "Thailand",       flag: "🇹🇭" },
  TJ: { name: "Tajikistan",     flag: "🇹🇯" },
  TM: { name: "Turkmenistan",   flag: "🇹🇲" },
  TR: { name: "Turkey",         flag: "🇹🇷" },
  TW: { name: "Taiwan",         flag: "🇹🇼" },
  UZ: { name: "Uzbekistan",     flag: "🇺🇿" },
  VN: { name: "Vietnam",        flag: "🇻🇳" },
  YE: { name: "Yemen",          flag: "🇾🇪" },

  // Europe
  AD: { name: "Andorra",                  flag: "🇦🇩" },
  AL: { name: "Albania",                  flag: "🇦🇱" },
  AT: { name: "Austria",                  flag: "🇦🇹" },
  BA: { name: "Bosnia and Herzegovina",   flag: "🇧🇦" },
  BE: { name: "Belgium",                  flag: "🇧🇪" },
  BG: { name: "Bulgaria",                 flag: "🇧🇬" },
  BY: { name: "Belarus",                  flag: "🇧🇾" },
  CH: { name: "Switzerland",              flag: "🇨🇭" },
  CY: { name: "Cyprus",                   flag: "🇨🇾" },
  CZ: { name: "Czech Republic",           flag: "🇨🇿" },
  DE: { name: "Germany",                  flag: "🇩🇪" },
  DK: { name: "Denmark",                  flag: "🇩🇰" },
  EE: { name: "Estonia",                  flag: "🇪🇪" },
  ES: { name: "Spain",                    flag: "🇪🇸" },
  FI: { name: "Finland",                  flag: "🇫🇮" },
  FR: { name: "France",                   flag: "🇫🇷" },
  GB: { name: "United Kingdom",           flag: "🇬🇧" },
  GR: { name: "Greece",                   flag: "🇬🇷" },
  HR: { name: "Croatia",                  flag: "🇭🇷" },
  HU: { name: "Hungary",                  flag: "🇭🇺" },
  IE: { name: "Ireland",                  flag: "🇮🇪" },
  IS: { name: "Iceland",                  flag: "🇮🇸" },
  IT: { name: "Italy",                    flag: "🇮🇹" },
  LI: { name: "Liechtenstein",            flag: "🇱🇮" },
  LT: { name: "Lithuania",               flag: "🇱🇹" },
  LU: { name: "Luxembourg",              flag: "🇱🇺" },
  LV: { name: "Latvia",                   flag: "🇱🇻" },
  MC: { name: "Monaco",                   flag: "🇲🇨" },
  MD: { name: "Moldova",                  flag: "🇲🇩" },
  ME: { name: "Montenegro",              flag: "🇲🇪" },
  MK: { name: "North Macedonia",          flag: "🇲🇰" },
  MT: { name: "Malta",                    flag: "🇲🇹" },
  NL: { name: "Netherlands",             flag: "🇳🇱" },
  NO: { name: "Norway",                   flag: "🇳🇴" },
  PL: { name: "Poland",                   flag: "🇵🇱" },
  PT: { name: "Portugal",                 flag: "🇵🇹" },
  RO: { name: "Romania",                  flag: "🇷🇴" },
  RS: { name: "Serbia",                   flag: "🇷🇸" },
  RU: { name: "Russia",                   flag: "🇷🇺" },
  SE: { name: "Sweden",                   flag: "🇸🇪" },
  SI: { name: "Slovenia",                 flag: "🇸🇮" },
  SK: { name: "Slovakia",                 flag: "🇸🇰" },
  UA: { name: "Ukraine",                  flag: "🇺🇦" },
  VA: { name: "Vatican City",             flag: "🇻🇦" },

  // America
  AR: { name: "Argentina",            flag: "🇦🇷" },
  BB: { name: "Barbados",             flag: "🇧🇧" },
  BO: { name: "Bolivia",              flag: "🇧🇴" },
  BR: { name: "Brazil",               flag: "🇧🇷" },
  BS: { name: "Bahamas",              flag: "🇧🇸" },
  BZ: { name: "Belize",               flag: "🇧🇿" },
  CA: { name: "Canada",               flag: "🇨🇦" },
  CL: { name: "Chile",                flag: "🇨🇱" },
  CO: { name: "Colombia",             flag: "🇨🇴" },
  CR: { name: "Costa Rica",           flag: "🇨🇷" },
  CU: { name: "Cuba",                 flag: "🇨🇺" },
  DM: { name: "Dominica",             flag: "🇩🇲" },
  DO: { name: "Dominican Republic",   flag: "🇩🇴" },
  EC: { name: "Ecuador",              flag: "🇪🇨" },
  GD: { name: "Grenada",              flag: "🇬🇩" },
  GT: { name: "Guatemala",            flag: "🇬🇹" },
  GY: { name: "Guyana",               flag: "🇬🇾" },
  HN: { name: "Honduras",             flag: "🇭🇳" },
  HT: { name: "Haiti",                flag: "🇭🇹" },
  JM: { name: "Jamaica",              flag: "🇯🇲" },
  MX: { name: "Mexico",               flag: "🇲🇽" },
  NI: { name: "Nicaragua",            flag: "🇳🇮" },
  PA: { name: "Panama",               flag: "🇵🇦" },
  PE: { name: "Peru",                 flag: "🇵🇪" },
  PY: { name: "Paraguay",             flag: "🇵🇾" },
  SR: { name: "Suriname",             flag: "🇸🇷" },
  SV: { name: "El Salvador",          flag: "🇸🇻" },
  TT: { name: "Trinidad and Tobago",  flag: "🇹🇹" },
  US: { name: "United States",        flag: "🇺🇸" },
  UY: { name: "Uruguay",              flag: "🇺🇾" },
  VE: { name: "Venezuela",            flag: "🇻🇪" },

  // Africa
  AO: { name: "Angola",                    flag: "🇦🇴" },
  BF: { name: "Burkina Faso",              flag: "🇧🇫" },
  BI: { name: "Burundi",                   flag: "🇧🇮" },
  BJ: { name: "Benin",                     flag: "🇧🇯" },
  BW: { name: "Botswana",                  flag: "🇧🇼" },
  CD: { name: "DR Congo",                  flag: "🇨🇩" },
  CF: { name: "Central African Republic",  flag: "🇨🇫" },
  CG: { name: "Congo",                     flag: "🇨🇬" },
  CI: { name: "Ivory Coast",               flag: "🇨🇮" },
  CM: { name: "Cameroon",                  flag: "🇨🇲" },
  CV: { name: "Cape Verde",                flag: "🇨🇻" },
  DJ: { name: "Djibouti",                  flag: "🇩🇯" },
  DZ: { name: "Algeria",                   flag: "🇩🇿" },
  EG: { name: "Egypt",                     flag: "🇪🇬" },
  ER: { name: "Eritrea",                   flag: "🇪🇷" },
  ET: { name: "Ethiopia",                  flag: "🇪🇹" },
  GA: { name: "Gabon",                     flag: "🇬🇦" },
  GH: { name: "Ghana",                     flag: "🇬🇭" },
  GM: { name: "Gambia",                    flag: "🇬🇲" },
  GN: { name: "Guinea",                    flag: "🇬🇳" },
  GQ: { name: "Equatorial Guinea",         flag: "🇬🇶" },
  GW: { name: "Guinea-Bissau",             flag: "🇬🇼" },
  KE: { name: "Kenya",                     flag: "🇰🇪" },
  KM: { name: "Comoros",                   flag: "🇰🇲" },
  LR: { name: "Liberia",                   flag: "🇱🇷" },
  LS: { name: "Lesotho",                   flag: "🇱🇸" },
  LY: { name: "Libya",                     flag: "🇱🇾" },
  MA: { name: "Morocco",                   flag: "🇲🇦" },
  MG: { name: "Madagascar",               flag: "🇲🇬" },
  ML: { name: "Mali",                      flag: "🇲🇱" },
  MR: { name: "Mauritania",               flag: "🇲🇷" },
  MU: { name: "Mauritius",                flag: "🇲🇺" },
  MW: { name: "Malawi",                    flag: "🇲🇼" },
  MZ: { name: "Mozambique",               flag: "🇲🇿" },
  NA: { name: "Namibia",                   flag: "🇳🇦" },
  NE: { name: "Niger",                     flag: "🇳🇪" },
  NG: { name: "Nigeria",                   flag: "🇳🇬" },
  RW: { name: "Rwanda",                    flag: "🇷🇼" },
  SC: { name: "Seychelles",               flag: "🇸🇨" },
  SD: { name: "Sudan",                     flag: "🇸🇩" },
  SL: { name: "Sierra Leone",             flag: "🇸🇱" },
  SN: { name: "Senegal",                   flag: "🇸🇳" },
  SO: { name: "Somalia",                   flag: "🇸🇴" },
  SS: { name: "South Sudan",              flag: "🇸🇸" },
  ST: { name: "Sao Tome and Principe",    flag: "🇸🇹" },
  SZ: { name: "Eswatini",                  flag: "🇸🇿" },
  TD: { name: "Chad",                      flag: "🇹🇩" },
  TG: { name: "Togo",                      flag: "🇹🇬" },
  TN: { name: "Tunisia",                   flag: "🇹🇳" },
  TZ: { name: "Tanzania",                  flag: "🇹🇿" },
  UG: { name: "Uganda",                    flag: "🇺🇬" },
  ZA: { name: "South Africa",             flag: "🇿🇦" },
  ZM: { name: "Zambia",                    flag: "🇿🇲" },
  ZW: { name: "Zimbabwe",                  flag: "🇿🇼" },

  // Oceania
  AU: { name: "Australia",         flag: "🇦🇺" },
  FJ: { name: "Fiji",              flag: "🇫🇯" },
  KI: { name: "Kiribati",          flag: "🇰🇮" },
  MH: { name: "Marshall Islands",  flag: "🇲🇭" },
  FM: { name: "Micronesia",        flag: "🇫🇲" },
  NR: { name: "Nauru",             flag: "🇳🇷" },
  NZ: { name: "New Zealand",       flag: "🇳🇿" },
  PW: { name: "Palau",             flag: "🇵🇼" },
  PG: { name: "Papua New Guinea",  flag: "🇵🇬" },
  WS: { name: "Samoa",             flag: "🇼🇸" },
  SB: { name: "Solomon Islands",   flag: "🇸🇧" },
  TO: { name: "Tonga",             flag: "🇹🇴" },
  TV: { name: "Tuvalu",            flag: "🇹🇻" },
  VU: { name: "Vanuatu",           flag: "🇻🇺" },
};

export async function GET(req: NextRequest) {
  try {
    const country =
      req.headers.get("x-vercel-ip-country") ??
      req.headers.get("cf-ipcountry") ??
      req.headers.get("x-country-code") ??
      "MY";

    const code = country.toUpperCase();
    const info = COUNTRIES[code] ?? { name: code, flag: "🏳️" };

    return NextResponse.json({
      success: true,
      data: { code, name: info.name, flag: info.flag },
    });
  } catch {
    return NextResponse.json({
      success: true,
      data: { code: "MY", name: "Malaysia", flag: "🇲🇾" },
    });
  }
}